services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: videodb
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -padmin --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  api:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n12045098-y-mini-api:latest
    env_file: .env
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: videodb
    ports:
      - "8080:4000"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  dbdata: